/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package location.views;

import location.dao.AssuranceDAO;
import location.dao.VoitureDAO;
import location.models.Assurance;
import location.models.Voiture;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author onsai
 */
public class FicheModifVoiture extends javax.swing.JFrame {

    /**
     * Creates new form FicheModifVoiture
     */
    private Voiture voitureOrigine;
    public FicheModifVoiture() {
        initComponents();
        

    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        immatModif = new javax.swing.JTextField();
        marqueModif = new javax.swing.JTextField();
        modeleModif = new javax.swing.JTextField();
        anneeModif = new javax.swing.JTextField();
        etatModif = new javax.swing.JComboBox<>();
        prixModif = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        carburantModif = new javax.swing.JComboBox<>();
        transMission = new javax.swing.JComboBox<>();
        debutAssModif = new javax.swing.JTextField();
        expirAssModif = new javax.swing.JTextField();
        idAssModif = new javax.swing.JComboBox<>();
        enregVoitModifBtn = new javax.swing.JButton();
        suppVoitBtn = new javax.swing.JButton();
        FermerModifBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        dispoModif = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Fiche Voiture");

        jLabel2.setText("Immatriculation : ");

        jLabel3.setText("Marque :");

        jLabel4.setText("Modèle :");

        jLabel5.setText("Année :");

        jLabel7.setText("Prix jour :");

        jLabel8.setText("Carburant :");

        jLabel9.setText("Transmission :");

        jLabel10.setText("Date début assurance :");

        jLabel11.setText("Date expiration assurance :");

        jLabel12.setText("ID assurance :");

        etatModif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "en_marche", "en_panne" }));

        jLabel13.setText("Etat :");

        carburantModif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "essence", "diesel", "electrique" }));

        transMission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "automatique", "manuel" }));

        enregVoitModifBtn.setText("Enregistrer");
        enregVoitModifBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregVoitModifBtnActionPerformed(evt);
            }
        });

        suppVoitBtn.setText("Supprimer");
        suppVoitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppVoitBtnActionPerformed(evt);
            }
        });

        FermerModifBtn.setText("Fermer");
        FermerModifBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FermerModifBtnActionPerformed(evt);
            }
        });

        jLabel14.setText("Disponibilite :");

        dispoModif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "disponible", "louee", "indisponible" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FermerModifBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(immatModif)
                                    .addComponent(marqueModif)
                                    .addComponent(modeleModif)
                                    .addComponent(anneeModif)
                                    .addComponent(prixModif)
                                    .addComponent(etatModif, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(carburantModif, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(transMission, 0, 169, Short.MAX_VALUE)
                                    .addComponent(debutAssModif)
                                    .addComponent(expirAssModif)
                                    .addComponent(idAssModif, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dispoModif, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(enregVoitModifBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(suppVoitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(immatModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marqueModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeleModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anneeModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etatModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dispoModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prixModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carburantModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transMission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(debutAssModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expirAssModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idAssModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(suppVoitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(enregVoitModifBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FermerModifBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void setVoitureOrigine(Voiture v) {
    this.voitureOrigine = v;

    // Remplir les champs de texte
    immatModif.setText(v.getImmatriculation());
    marqueModif.setText(v.getMarque());
    modeleModif.setText(v.getModele());
    anneeModif.setText(String.valueOf(v.getAnnee()));
    prixModif.setText(String.valueOf(v.getPrixJour()));
    debutAssModif.setText(v.getDateDebutAssurance().toString());
    expirAssModif.setText(v.getDateExpirationAssurance().toString());

    // Remplir les combo box
    carburantModif.setSelectedItem(v.getCarburant());
    transMission.setSelectedItem(v.getTransmission());
    etatModif.setSelectedItem(v.getEtat());
    dispoModif.setSelectedItem(v.getDisponibilite());
    idAssModif.setSelectedItem(String.valueOf(v.getIdAssurance()));
}
    void chargerIdAssurances() {
    AssuranceDAO dao = new AssuranceDAO();
    List<Assurance> assurances = dao.getAllAssurances();

    idAssModif.removeAllItems(); // vider le combo box

    for (Assurance assurance : assurances) {
        idAssModif.addItem(String.valueOf(assurance.getIdAssurance()));
    }
    idAssModif.revalidate();
    idAssModif.repaint();

}
public void remplirChamps(Voiture voiture) {
    immatModif.setText(voiture.getImmatriculation());
    marqueModif.setText(voiture.getMarque());
    modeleModif.setText(voiture.getModele());
    anneeModif.setText(String.valueOf(voiture.getAnnee()));
    prixModif.setText(String.valueOf(voiture.getPrixJour()));
    debutAssModif.setText(String.valueOf(voiture.getDateDebutAssurance()));
    expirAssModif.setText(String.valueOf(voiture.getDateExpirationAssurance()));

    etatModif.setSelectedItem(voiture.getEtat());
    carburantModif.setSelectedItem(voiture.getCarburant());
    transMission.setSelectedItem(voiture.getTransmission());
    idAssModif.setSelectedItem(String.valueOf(voiture.getIdAssurance())); // combo box rempli avant
}


    private void enregVoitModifBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregVoitModifBtnActionPerformed
          if (marqueModif.getText().isEmpty() || modeleModif.getText().isEmpty() ||
        anneeModif.getText().isEmpty() || prixModif.getText().isEmpty() ||
        debutAssModif.getText().isEmpty() || expirAssModif.getText().isEmpty()) {

        JOptionPane.showMessageDialog(this, "Tous les champs doivent être remplis.", "Champs manquants", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        // Récupérer les données
        String immat = voitureOrigine.getImmatriculation(); // champ non modifiable
        String marque = marqueModif.getText();
        String modele = modeleModif.getText();
        int annee = Integer.parseInt(anneeModif.getText());
        double prixJour = Double.parseDouble(prixModif.getText());
        String etat = etatModif.getSelectedItem().toString();
        String carburant = carburantModif.getSelectedItem().toString();
        String transmission = transMission.getSelectedItem().toString();
        String disponibilite = dispoModif.getSelectedItem().toString();
        int idAssurance = Integer.parseInt(idAssModif.getSelectedItem().toString());

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date debutAss = sdf.parse(debutAssModif.getText());
        Date expAss = sdf.parse(expirAssModif.getText());

        // Construire objet voiture modifiée
        Voiture voitureModifiee = new Voiture(
            immat, marque, modele, annee, etat, disponibilite,
            prixJour, carburant, transmission, debutAss, expAss, idAssurance
        );

        // Mise à jour via DAO
        VoitureDAO voitureDAO = new VoitureDAO();
boolean modif = voitureDAO.modifier(voitureModifiee);


        if (modif) {
            JOptionPane.showMessageDialog(this, "Voiture modifiée avec succès !");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Échec de la modification.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
    }                                   
       
    }//GEN-LAST:event_enregVoitModifBtnActionPerformed

    private void suppVoitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppVoitBtnActionPerformed
     int confirmation = JOptionPane.showConfirmDialog(this, 
        "Êtes-vous sûr de vouloir supprimer cette voiture ?", 
        "Confirmation de suppression", 
        JOptionPane.YES_NO_OPTION);

    if (confirmation == JOptionPane.YES_OPTION) {
        VoitureDAO voitureDAO = new VoitureDAO(); // création de l'objet DAO
        boolean supprimee = voitureDAO.supprimer(voitureOrigine.getImmatriculation());

        if (supprimee) {
            JOptionPane.showMessageDialog(this, "Voiture supprimée avec succès !");
            this.dispose(); // fermer la fenêtre
        } else {
            JOptionPane.showMessageDialog(this, "Échec de la suppression.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_suppVoitBtnActionPerformed

    private void FermerModifBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FermerModifBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_FermerModifBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FicheModifVoiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FicheModifVoiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FicheModifVoiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FicheModifVoiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FicheModifVoiture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FermerModifBtn;
    private javax.swing.JTextField anneeModif;
    private javax.swing.JComboBox<String> carburantModif;
    private javax.swing.JTextField debutAssModif;
    private javax.swing.JComboBox<String> dispoModif;
    private javax.swing.JButton enregVoitModifBtn;
    private javax.swing.JComboBox<String> etatModif;
    private javax.swing.JTextField expirAssModif;
    private javax.swing.JComboBox<String> idAssModif;
    private javax.swing.JTextField immatModif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField marqueModif;
    private javax.swing.JTextField modeleModif;
    private javax.swing.JTextField prixModif;
    private javax.swing.JButton suppVoitBtn;
    private javax.swing.JComboBox<String> transMission;
    // End of variables declaration//GEN-END:variables

    
}
