/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package location.views;

import location.dao.AssuranceDAO;
import location.dao.VoitureDAO;
import location.models.Assurance;
import location.models.Voiture;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author onsai
 */
public class FicheAjoutVoiture extends javax.swing.JFrame {

    /**
     * Creates new form FicheModifVoiture
     */
    
    public FicheAjoutVoiture() {
        initComponents();
        chargerIdAssurances();
        resetChamps();
        

    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        immatAjout = new javax.swing.JTextField();
        marqueAjout = new javax.swing.JTextField();
        modeleAjout = new javax.swing.JTextField();
        anneeAjout = new javax.swing.JTextField();
        etatAjout = new javax.swing.JComboBox<>();
        prixAjout = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        carburantAjout = new javax.swing.JComboBox<>();
        transAjout = new javax.swing.JComboBox<>();
        debutAssAjout = new javax.swing.JTextField();
        expirAssAjout = new javax.swing.JTextField();
        idAssAjout = new javax.swing.JComboBox<>();
        enregVoitAjoutBtn = new javax.swing.JButton();
        FermerModifBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        dispoAjout = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Fiche Voiture");

        jLabel2.setText("Immatriculation : ");

        jLabel3.setText("Marque :");

        jLabel4.setText("Modèle :");

        jLabel5.setText("Année :");

        jLabel7.setText("Prix jour :");

        jLabel8.setText("Carburant :");

        jLabel9.setText("Transmission :");

        jLabel10.setText("Date début assurance :");

        jLabel11.setText("Date expiration assurance :");

        jLabel12.setText("ID assurance :");

        etatAjout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "en_marche", "en_panne" }));

        jLabel13.setText("Etat :");

        carburantAjout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "essence", "diesel", "electrique" }));

        transAjout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "automatique", "manuel" }));

        idAssAjout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        enregVoitAjoutBtn.setText("Enregistrer");
        enregVoitAjoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregVoitAjoutBtnActionPerformed(evt);
            }
        });

        FermerModifBtn.setText("Fermer");
        FermerModifBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FermerModifBtnActionPerformed(evt);
            }
        });

        jLabel14.setText("Disponibilite :");

        dispoAjout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "disponible", "louee", "indisponible" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FermerModifBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(immatAjout)
                                    .addComponent(marqueAjout)
                                    .addComponent(modeleAjout)
                                    .addComponent(anneeAjout)
                                    .addComponent(prixAjout)
                                    .addComponent(etatAjout, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(carburantAjout, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(transAjout, 0, 169, Short.MAX_VALUE)
                                    .addComponent(debutAssAjout)
                                    .addComponent(expirAssAjout)
                                    .addComponent(idAssAjout, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dispoAjout, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(enregVoitAjoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 279, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(immatAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marqueAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeleAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anneeAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etatAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dispoAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prixAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carburantAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(debutAssAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expirAssAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idAssAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(enregVoitAjoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FermerModifBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void resetChamps() {
    immatAjout.setText("");
    marqueAjout.setText("");
    modeleAjout.setText("");
    anneeAjout.setText("");
    prixAjout.setText("");
    debutAssAjout.setText("");
    expirAssAjout.setText("");

    carburantAjout.setSelectedIndex(0);
    dispoAjout.setSelectedIndex(0);
    etatAjout.setSelectedIndex(0);
    transAjout.setSelectedIndex(0);
}

    void chargerIdAssurances() {
    AssuranceDAO dao = new AssuranceDAO();
    List<Assurance> assurances = dao.getAllAssurances();

    idAssAjout.removeAllItems(); // vider le combo box

    for (Assurance assurance : assurances) {
        idAssAjout.addItem(String.valueOf(assurance.getIdAssurance()));
    }
}



    private void enregVoitAjoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregVoitAjoutBtnActionPerformed
        if (immatAjout.getText().isEmpty() || marqueAjout.getText().isEmpty() ||
            modeleAjout.getText().isEmpty() || anneeAjout.getText().isEmpty() ||
            prixAjout.getText().isEmpty() || debutAssAjout.getText().isEmpty() ||
            expirAssAjout.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs obligatoires.");
            return;
        }

        try {
            // Récupération des valeurs
            String immat = immatAjout.getText().trim();
            String marque = marqueAjout.getText().trim();
            String modele = modeleAjout.getText().trim();
            int annee = Integer.parseInt(anneeAjout.getText().trim());
            double prixJour = Double.parseDouble(prixAjout.getText().trim());
            String etat = (String) etatAjout.getSelectedItem();
            String dispo = (String) dispoAjout.getSelectedItem();
            String carburant = (String) carburantAjout.getSelectedItem();
            String transmission = (String) transAjout.getSelectedItem();
            String idAssStr = (String) idAssAjout.getSelectedItem();
            int idAssurance = Integer.parseInt(idAssStr);

            // Conversion des dates (au format yyyy-MM-dd)
            java.sql.Date dateDebutAss = java.sql.Date.valueOf(debutAssAjout.getText().trim());
            java.sql.Date dateExpirAss = java.sql.Date.valueOf(expirAssAjout.getText().trim());

            // Création de l'objet voiture
            Voiture voiture = new Voiture(immat, marque, modele, annee,etat, dispo,prixJour, carburant, transmission,dateDebutAss, dateExpirAss, idAssurance);

            // Insertion via DAO
            VoitureDAO dao = new VoitureDAO();
            boolean success = dao.ajouterVoiture(voiture);

            if (success) {
                JOptionPane.showMessageDialog(null, "Voiture ajoutée avec succès !");
                dispose(); // Ferme la fenêtre
            } else {
                JOptionPane.showMessageDialog(null, "Erreur lors de l'ajout de la voiture.");
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Erreur de format numérique (année, prix ou ID assurance).");
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, "Format de date incorrect. Utilisez yyyy-MM-dd.");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erreur inattendue : " + ex.getMessage());
        }
    
    }//GEN-LAST:event_enregVoitAjoutBtnActionPerformed

    private void FermerModifBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FermerModifBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_FermerModifBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FicheAjoutVoiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FicheAjoutVoiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FicheAjoutVoiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FicheAjoutVoiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FicheAjoutVoiture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FermerModifBtn;
    private javax.swing.JTextField anneeAjout;
    private javax.swing.JComboBox<String> carburantAjout;
    private javax.swing.JTextField debutAssAjout;
    private javax.swing.JComboBox<String> dispoAjout;
    private javax.swing.JButton enregVoitAjoutBtn;
    private javax.swing.JComboBox<String> etatAjout;
    private javax.swing.JTextField expirAssAjout;
    private javax.swing.JComboBox<String> idAssAjout;
    private javax.swing.JTextField immatAjout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField marqueAjout;
    private javax.swing.JTextField modeleAjout;
    private javax.swing.JTextField prixAjout;
    private javax.swing.JComboBox<String> transAjout;
    // End of variables declaration//GEN-END:variables

    
}
