/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package location.views;

import javax.swing.JOptionPane;
import location.models.Client;
import location.models.Utilisateur;
import location.dao.ClientDAO;
import location.dao.UtilisateurDAO;
import location.utils.DatabaseConnection;
// Nécessaire pour la redirection après connexion
import location.views.ClientDashboard;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import location.dao.PersonalDAO;
import location.dao.PersonnelDAO;

/**
 *
 * @author sahar
 */
public class loginframe extends javax.swing.JFrame {

    /**
     * Creates new form loginframe
     */
    public loginframe() {
        initComponents();
        joublier.setForeground(java.awt.Color.BLUE);
        joublier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        joublier.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            AuthentificationFrame recoveryFrame = new AuthentificationFrame();
        recoveryFrame.setVisible(true);
    }
});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // Initialisation des composants
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jusername = new javax.swing.JTextField();
        jpassword = new javax.swing.JPasswordField();
        blogin = new javax.swing.JButton();
        bretour = new javax.swing.JButton();
        joublier = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Se connnecter à votre compte");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 225, 56));

        jLabel2.setText("Adresse e-mail");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 136, 27));

        jLabel3.setText("Mot de passe");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 136, 42));

        jusername.setText("client");
        jusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jusernameActionPerformed(evt);
            }
        });
        getContentPane().add(jusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 191, -1));

        jpassword.setText("password123");
        getContentPane().add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 191, -1));

        blogin.setText("Se connecter");
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });
        getContentPane().add(blogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        bretour.setText("Annuler");
        bretour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bretourActionPerformed(evt);
            }
        });
        getContentPane().add(bretour, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 294, -1, -1));

        joublier.setText("Informations de compte oubliées?");
        getContentPane().add(joublier, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 296, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "personnel", "client" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 191, -1));

        jLabel4.setText("Type utilisateur");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed
        // Code pour la connexion
        
        
        
        String email = jusername.getText().trim();
        String password = new String(jpassword.getPassword());
        
        // Afficher les données de debug dans la console
        System.out.println("===== TENTATIVE DE CONNEXION =====");
        System.out.println("Email saisi: " + email);
        System.out.println("Longueur du mot de passe: " + password.length());
        
        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez saisir un email et un mot de passe", 
                "Champs obligatoires", 
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        // Déterminer si le mot de passe est une CIN (client) ou un mot de passe normal (utilisateur)
        boolean isCIN = password.matches("\\d+"); // Vérifier si le mot de passe ne contient que des chiffres
        System.out.println("Le mot de passe est-il une CIN? " + isCIN);
        
        int cin = -1;
        
        if (isCIN) {
            try {
                cin = Integer.parseInt(password);
                System.out.println("CIN convertie en entier: " + cin);
            } catch (NumberFormatException e) {
                System.err.println("Erreur de conversion de la CIN: " + e.getMessage());
                JOptionPane.showMessageDialog(this, "Format de CIN invalide", "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        var v = new UtilisateurDAO();
        var user = v.authentifier(email, password);
        if(user != null){
            var t = jComboBox1.getSelectedItem().toString();
            switch (t) {
                case "client":
                    var client = new ClientDAO().trouverParCIN(user.getCin());
                    if(client != null)
                    {
                        var clientDashboard = new ClientDashboard2(user);
                        clientDashboard.setVisible(true);
                            this.dispose(); // Fermer l'écran de connexion
                            return;
                    }
                            
                    break;
                case "personnel":
                                    //ClientDashboard clientDashboard = new ClientDashboard(user);
                var pdao = new PersonnelDAO();
                var p = pdao.trouverParCin(user.getCin());
                if(p != null && "admin".equals(p.getRole())){
                    var dashboardFrame = new AdminDashboard(user);
                dashboardFrame.setVisible(true);
                this.dispose(); // Fermer l'écran de connexion
                return;
                    
                }
                if( p != null && "employe".equals(p.getRole())){
                    var dashboardFrame = new EspaceEmploye(user);
                dashboardFrame.setVisible(true);
                this.dispose(); // Fermer l'écran de connexion
                return;
                    
                }
                JOptionPane.showMessageDialog(this, 
                "Veuillez saisir un type correct", 
                "Champs faux", 
                JOptionPane.INFORMATION_MESSAGE);
                
                default:
                      JOptionPane.showMessageDialog(this, 
                "Veuillez saisir un type correct", 
                "Champs faux", 
                JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_bloginActionPerformed

    private void jusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jusernameActionPerformed
        // TODO add your handling code here:
        if (jusername.getText().trim().isEmpty()) {
            jusername.setText("nom@example.com");
        }
         
    }//GEN-LAST:event_jusernameActionPerformed

    private void bretourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bretourActionPerformed
        // TODO add your handling code here:
        new HomeFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bretourActionPerformed
    
    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }
    
    private void bregisterActionPerformed(java.awt.event.ActionEvent evt) {
        // Ouvrir la fenêtre d'inscription
        RegisterFrame registerFrame = new RegisterFrame();
        registerFrame.setVisible(true);
        this.setVisible(false);
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginframe().setVisible(true);
            }
        });
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blogin;
    private javax.swing.JButton bretour;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel joublier;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jusername;
    // End of variables declaration//GEN-END:variables
}
