/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package location.views;

import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.Calendar;
import java.util.Date;
import location.dao.ClientDAO;
import location.dao.UtilisateurDAO;
import location.dao.VoitureDAO;
import location.models.Client;
import location.models.Voiture;

/**
 *
 * @author sahar
 */
public class ReservationFrame extends javax.swing.JFrame {

    Voiture voiture;
    int cin;
    ClientDashboard2 d2;
    /**
     * Creates new form ReservationFrame
     */
    public ReservationFrame(String immatriculation, int cin, ClientDashboard2 d2) {
        initComponents();
        voiture = new VoitureDAO().trouverParImmatriculation(immatriculation);
        this.cin = cin;
        this.d2 = d2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        montantLocationField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        button2 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button1.setActionCommand("annuler");
        button1.setLabel("Annuler");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Date Debut ");

        jLabel2.setText("Date Fin");

        jLabel3.setText("Details Reservation ");

        jLabel4.setText("Montant location");

        montantLocationField.setEnabled(false);
        montantLocationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montantLocationFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Mode paiement");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "application D17", "carte bancaire" }));

        button2.setActionCommand("payer");
        button2.setLabel("Payer");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel3))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(montantLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(montantLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        var localDate = LocalDate.now();
          Date debut = Date.from(localDate.atStartOfDay(ZoneId.systemDefault()).toInstant());

          Date fin = Date.from(localDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
        //new business().reserver(voiture, cin, debut, fin);
        if(d2 != null) d2.update() ;
        this.dispose();
        
    }//GEN-LAST:event_button1ActionPerformed

    private void montantLocationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montantLocationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montantLocationFieldActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
         var localDate = LocalDate.now();
          Date debut = jDateChooser1.getDate();
          Date fin = jDateChooser2.getDate();
          
          
          
         
        new business().reserver(voiture, cin, debut, fin, jComboBox1.getSelectedItem().toString());
        if(d2 != null) d2.update();
    }//GEN-LAST:event_button2ActionPerformed

    private boolean checkDate(){
        Date debut = jDateChooser1.getDate();
          Date fin = jDateChooser2.getDate();
           return (debut != null && fin != null  && debut.before(fin));
    }
    
     private void updatePrix(){
            Date debut = jDateChooser1.getDate();
          Date fin = jDateChooser2.getDate();
          long daysBetween = 0;
          if (checkDate()){
              LocalDate date1 = debut.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate date2 = fin.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

         daysBetween = ChronoUnit.DAYS.between(date1, date2);
          }
          
        montantLocationField.setText(String.valueOf((voiture.getPrixJour()*daysBetween)));
          
  
          
     }
     
    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
            if ("date".equals(evt.getPropertyName())) {
                
                    if(jDateChooser2.getDate() == null){
                        var fin = jDateChooser1.getDate();
                        Calendar calendar = Calendar.getInstance();
        calendar.setTime(fin);
        calendar.add(Calendar.DAY_OF_MONTH, 1);
        jDateChooser2.setDate(calendar.getTime());
                    }
                     updatePrix();
                    
            }
       
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jDateChooser2VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jDateChooser2VetoableChange
        
    }//GEN-LAST:event_jDateChooser2VetoableChange

    private void jDateChooser2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser2PropertyChange
        // TODO add your handling code here:
        // TODO add your handling code here:
         if ("date".equals(evt.getPropertyName())) {
                
                    if(jDateChooser1.getDate() == null){
                        var fin = jDateChooser2.getDate();
                        Calendar calendar = Calendar.getInstance();
        calendar.setTime(fin);
        calendar.add(Calendar.DAY_OF_MONTH, -1);
        jDateChooser1.setDate(calendar.getTime());
                    }
                    
                    updatePrix();
                    
            }
    }//GEN-LAST:event_jDateChooser2PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String immatriculation = new VoitureDAO().listerTout().get(0).getImmatriculation();
                var c = new ClientDAO().listerTous().get(0);
                new ReservationFrame(immatriculation, c.getCin(), null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField montantLocationField;
    // End of variables declaration//GEN-END:variables
}
